//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsNet45 : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsNet45 defaultInstance = ((SettingsNet45)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsNet45())));
        
        public static SettingsNet45 Default {
            get {
                return defaultInstance;
            }
        }
    }
}
